# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ToitAnalyzerRDC
                                 A QGIS plugin
 Module de comptage géospatial des toits
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-12
        copyright            : (C) 2026 by Benjamin Katende
        email                : benjamin.katende@anser.gouv.cd
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ToitAnalyzerRDC class from file ToitAnalyzerRDC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .toit_analyzer_rdc import ToitAnalyzerRDC
    return ToitAnalyzerRDC(iface)
